name: note_app1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get: ^4.7.2
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  path: ^1.9.1
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  connectivity_plus: ^6.1.4
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.0
  firebase_auth: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
