// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPTu5wBaE00iFNEFnp5iGzmHrvzu8rtlU',
    appId: '1:295598486393:web:9aeaf0ce510b26961af5a8',
    messagingSenderId: '295598486393',
    projectId: 'noteapp-d667e',
    authDomain: 'noteapp-d667e.firebaseapp.com',
    storageBucket: 'noteapp-d667e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWsILno0iWWw8DZF9FdKiD98o1s6SfCY',
    appId: '1:295598486393:android:2d92c01b24b3e4091af5a8',
    messagingSenderId: '295598486393',
    projectId: 'noteapp-d667e',
    storageBucket: 'noteapp-d667e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Tw9A2axlNxsTdxJXCIPM5cEeelWdDoc',
    appId: '1:295598486393:ios:fb098a872dd648bc1af5a8',
    messagingSenderId: '295598486393',
    projectId: 'noteapp-d667e',
    storageBucket: 'noteapp-d667e.firebasestorage.app',
    iosBundleId: 'com.example.noteApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Tw9A2axlNxsTdxJXCIPM5cEeelWdDoc',
    appId: '1:295598486393:ios:fb098a872dd648bc1af5a8',
    messagingSenderId: '295598486393',
    projectId: 'noteapp-d667e',
    storageBucket: 'noteapp-d667e.firebasestorage.app',
    iosBundleId: 'com.example.noteApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPTu5wBaE00iFNEFnp5iGzmHrvzu8rtlU',
    appId: '1:295598486393:web:001a329621478ca01af5a8',
    messagingSenderId: '295598486393',
    projectId: 'noteapp-d667e',
    authDomain: 'noteapp-d667e.firebaseapp.com',
    storageBucket: 'noteapp-d667e.firebasestorage.app',
  );
}
